In [57]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Import classifiers and performance metrics
from sklearn import datasets, svm, metrics, preprocessing
from sklearn.model_selection import train_test_split
from mla.utils import one_hot


In [58]:

def process_x_y(x_data,y_data):
    
    ''' convert the text columns of np.arrays of desired x_data and y_data into int / vector representation '''
    
    # convert text columns to integer values
    to_int = [0,2,7]
    for i in to_int:
        temp = x_data[:,i]
        temp_fit = le.fit(temp)
        x_data[:,i] = le.transform(temp)

    for i in range(len(x_data)):
        for j in range(len(x_data[i])):
            if np.isnan(x_data[i][j]):
                x_data[i][j] = 0

    x_data = x_data.astype(int)

    y_fit = le.fit(y_data)
    y_data = le.transform(y_data)
    return x_data, y_data

In [59]:
csv_file = 'compas-scores-two-years-violent.csv'
df = pd.read_csv(csv_file)

keep = [
 'sex',
 'age',
 'race',
 'juv_fel_count',
 'juv_misd_count',
 'juv_other_count',
 'priors_count',
 'c_charge_degree']

target = ['v_score_text']

le = preprocessing.LabelEncoder()
y = df[target].as_matrix()
x = df[keep].as_matrix()

x_data, y_data = process_x_y(x,y)

print x_data.shape
print y_data.shape

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.15, random_state=1111)



(4743, 8)
(4743,)


In [60]:
# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)


In [61]:
classifier.fit(x_train, y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [64]:
expected = y_test
predicted = classifier.predict(x_test)

print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))


Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.50      0.02      0.04        54
          1       0.83      0.95      0.89       502
          2       0.62      0.54      0.58       156

avg / total       0.76      0.79      0.76       712


Confusion matrix:
[[  1  25  28]
 [  1 478  23]
 [  0  72  84]]
